module.exports = {
  campaign: require("./campaign.route"),
  category: require("./category.route"),
  // Generators
  character: require("./generators/character.route"),
  item: require("./generators/item.route"),
  monster: require("./generators/monster.route"),
  npc: require("./generators/npc.route"),
  plotHook: require("./generators/plotHook.route"),
  tavern: require("./generators/tavern.route"),
  town: require("./generators/town.route"),
  combat: require("./generators/combat.route"),
  // User
  profile: require("./profile.route"),
  user: require("./user.route"),
  // Admin
  admin: require("./admin/admin.route"),
  // NPCs
  quirk: require("./admin/generatorData/quirk.route"),
  activity: require("./admin/generatorData/activity.route"),
  // Character
  backstory: require("./admin/generatorData/character/backstory.route"),
  characterClass: require("./admin/generatorData/character/characterClass.route"),
  subclass: require("./admin/generatorData/character/subclass.route"),
  spell: require("./admin/generatorData/character/spell.route"),
  race: require("./admin/generatorData/character/race.route"),
  author: require("./admin/generatorData/character/author.route"),
  characterTrait: require("./admin/generatorData/character/characterTrait.route"),
  classTrait: require("./admin/generatorData/character/classTrait.route"),
  culture: require("./admin/generatorData/character/culture.route"),
  locale: require("./admin/generatorData/character/locale.route"),
  origin: require("./admin/generatorData/character/origin.route"),
  tone: require("./admin/generatorData/character/tone.route"),
  // Items
  itemEffect: require("./admin/generatorData/item/itemEffect.route"),
  itemCurse: require("./admin/generatorData/item/itemCurse.route"),
  // Plot Hooks
  plotHookData: require("./admin/generatorData/plotHookData/plotHookData.route"),
  // Tavern
  menuItem: require("./admin/generatorData/tavern/menuItem.route"),
  tavernAtmosphere: require("./admin/generatorData/tavern/tavernAtmosphere.route"),
  tavernEvent: require("./admin/generatorData/tavern/tavernEvent.route"),
  tavernFeature: require("./admin/generatorData/tavern/tavernFeature.route"),
  tavernRumor: require("./admin/generatorData/tavern/tavernRumor.route"),
  // Monster
  monsterData: require("./admin/generatorData/monster/monsterData.route"),
  monsterAbility: require("./admin/generatorData/monster/monsterAbility.route"),
};
