const test = [
  "Griffon Wing Ale: A strong, dark beer with a hint of smokiness, rumored to be brewed with a feather of a griffon for an extra kick.",
  "Dragonbreath Chili: A fiery stew made with a blend of exotic spices and a touch of dragon pepper. It's guaranteed to leave adventurers breathing fire.",
  "Mystic Mushroom Stew: A hearty bowl of stew made with rare mushrooms from the enchanted forest, served with a side of warm, herb-infused bread.",
  "Elixir of Euphoria: A sparkling, sweet beverage with a magical twist; each sip changes its flavor to the drinker's current mood.",
  "Pixie-Dusted Pheasant: A succulent roast pheasant with a light, crispy coating of pixie dust, giving it a subtle sparkle and enchanting taste.",
  'Basilisk Brisket: A tender brisket, slow-cooked in a stone oven. It\'s so good it could "petrify" your taste buds with delight.',
  "Dwarven Deep Pie: A deep-dish pie filled with rich meats, root vegetables, and a thick, savory gravy, topped with a flaky crust.",
  "Mermaid's Delight Sushi: An assortment of sushi featuring exotic seafood from the depths of the ocean, wrapped in magical seaweed that shimmers in the light.",
  "Goblin Gumbo: A spicy and hearty stew filled with various meats and vegetables, known for its unpredictable flavor bursts.",
  "Enchanted Elderberry Tart: A sweet tart made with elderberries picked under a full moon, giving it a mystical and irresistible flavor.",
  "Roc Egg Omelette: A giant omelette made from the egg of a roc, capable of feeding an entire party of adventurers.",
  "Celestial Salad: A light, refreshing salad made with rare herbs and vegetables, each bite fills you with a sense of peace and serenity.",
  "Lich's Lament Liquor: An ancient and potent spirit, said to be distilled from a recipe found in a lich's lair.",
  "Treant Truffle Toast: A decadent toast topped with shaved truffles from the enchanted forest, and a spread made from treant sap.",
  "Feywine Fondue: A bubbling pot of rich cheese infused with a dash of feywine, perfect for dipping bread, vegetables, or even enchanted meats.",
  "Abyssal Absinthe: A dark, potent drink that causes vivid hallucinations of the Underdark.",
  "Wizard's Whirlwind: A sparkling blue cocktail that creates a mini tornado inside the glass when stirred.",
  "Djinni's Delight: A mystical drink that changes color and flavor with each sip.",
  "Elven Moonwine: A sweet, luminescent wine made from moon-harvested grapes.",
  "Goblin Grog: A murky, strong brew with a surprisingly sweet aftertaste.",
  "Dwarven Fire Ale: A thick, amber ale that warms you from the inside like a forge.",
  "Siren's Sangria: A mesmerizing blend of fruits and wine that enchants the drinker's voice.",
  "Kraken Rum: A dark, spiced rum with a hint of sea salt and mystery.",
  "Valkyrie Vodka: A crystal-clear vodka that gives a feeling of weightlessness.",
  "Orcish Stout: A robust, bitter stout that's favored by warriors.",
  "Frost Giant's Icicle: A chilled, minty drink that numbs the mouth.",
  "Phoenix Fire Whiskey: A whiskey that leaves a trail of gentle flames on the surface.",
  "Fairy Fizz: A light, effervescent drink with a sprinkle of pixie dust on top.",
  "Necromancer's Nectar: A deep purple drink that seems to absorb light.",
  "Lycan Lager: A beer that brings out the animal in you, metaphorically speaking.",
  "Merfolk Mead: A sweet honey drink with a hint of the ocean.",
  "Satyr's Sangiovese: A rich red wine with a mischievous kick.",
  "Banshee Bourbon: A hauntingly smooth bourbon that echoes softly in the glass.",
  "Dragon's Breath Brandy: A brandy that leaves a smoky trail as it's poured.",
  "Centaur Cider: A hard cider with a hint of wild apples.",
  "Troll Tequila: A strong, greenish tequila with a regenerative effect on mood.",
  "Vampire's Veil: A deep red cocktail with a sharp, biting taste.",
  "Gnome Gin: A floral gin with a complex array of botanicals.",
  "Medusa's Malt: A malt drink that's said to be 'petrifyingly good'.",
  "Celestial Champagne: A divine drink with a golden glow that seems to dance in the glass.",
  "Elven Moonwine: A sweet, luminescent wine made from moon-harvested grapes.",
  "Dwarven Stout: A rich, dark beer with hints of coffee and chocolate, beloved by stout-hearted folk.",
  "Mead of the Ancients: A traditional honey mead with a secret blend of spices.",
  "Wizard's Whirlwind: A sparkling blue cocktail with a swirling mist effect.",
  "Red Dragon Ale: A fiery spiced ale with a smoky aftertaste.",
  "Gnomish Gin: A clear spirit with a vibrant mix of botanicals and a hint of magic.",
  "Ranger's Rum: A smooth, aged rum with a hint of wilderness flavors like oak and vanilla.",
  "Bard's Brandy: A fine, fruity brandy that inspires creativity and song.",
  "Sorcerer's Sangria: A magical sangria that subtly changes flavors as you drink.",
  "Common Ale: A staple in every tavern, easy to drink and always refreshing.",
  "Viking Vodka: A strong, clear spirit that emboldens even the meekest of souls.",
  "Frost Giant's Icicle: A chilling, mint-infused drink that cools even the hottest tempers.",
  "Cleric's Cider: A sweet apple cider with a touch of heavenly grace.",
  "Thieves' Guild Thistlewine: A rare wine with a prickly edge, favored by the stealthy and cunning.",
  "House Wine: Available in red or white, a reliable choice for any patron.",
  "Paladin's Pilsner: A light, crisp beer that upholds the highest standards of brewing.",
  "Whispering Whiskey: An aged whiskey that reveals hidden truths with each sip.",
  "Barbarian Brew: A potent, unrefined beer that's as wild as its name suggests.",
  "Pixie Punch: A fruity, potent cocktail with a sprinkling of shimmering dust.",
  "Monk's Meditation Malt: A soothing, malted beverage that aids in focus and relaxation.",
  "Sylvan Spritzer: A refreshing, lightly carbonated drink with a hint of forest berries.",
  "Tavern Tequila: A straightforward tequila, perfect for shots or mixed drinks.",
  "Warlock's Wine: A mysterious, dark wine with an enchanting aroma.",
  "Mermaid's Mojito: A light, aquatic twist on the classic mojito, with a hint of sea salt.",
  "Basic Bitter: A traditional bitter ale, reliable and satisfying.",
  "Goblin's Gold Lager: A golden, crisp lager with a slightly mischievous taste.",
  "Mystic Merlot: A deep, red wine with subtle magical undertones.",
  "Frostpeak IPA: A hoppy, refreshing IPA with a hint of mountain herbs.",
  "Siren's Song Cider: A sweet apple cider with an enchantingly melodious flavor.",
  "Draconic Dark Stout: A robust stout with a smoky, almost fiery aftertaste.",
  "Halfling Harvest Ale: A light ale brewed with seasonal fruits and a touch of honey.",
  "Witch's Brew Porter: A dark, mysterious porter with a bewitching blend of spices.",
  "Knight's Honor Kolsch: A crisp, clean kolsch that's as noble and steadfast as its namesake.",
  "Elven Elderflower Wine: A delicate, floral wine, reminiscent of ancient elven groves.",
  "Minotaur Malt Liquor: A strong, bold malt liquor with a labyrinth of flavors.",
  "Pixie Petal Rosé: A light, airy rosé with a subtle floral essence.",
  "Orcish Oatmeal Stout: A hearty stout with rich oatmeal notes, strong enough for any orc.",
  "Griffin's Grog Ale: A traditional ale with a hint of spice, as bold as the griffin itself.",
  "Nymph's Nectar Spritzer: A refreshing spritzer infused with a blend of natural forest essences.",
  "Centaur's Chalice Chardonnay: A balanced chardonnay, perfect for a toast or celebration.",
  "Dungeon Depths Red Blend: A deep, complex red blend, as mysterious as the dungeons it's named for.",
  "Pegasus Pinot Noir: A light, graceful pinot noir that seems to elevate the senses.",
  "Basilisk Bock Beer: A traditional bock, strong and smooth, with a gaze as captivating as the creature it's named after.",
  "Valkyrie's Victory Mead: A traditional honey mead with a victorious, bold flavor.",
  "Wizard's Wand Wheat Beer: A light, refreshing wheat beer with a hint of magic.",
  "Dragon's Den Shiraz: A bold shiraz, with a fiery temperament and a smoky finish.",
  "Gnome's Garden Gin: A botanical gin with hints of garden herbs and a touch of whimsy.",
  "Lich's Lair Lager: A dark, brooding lager with an intense and mysterious flavor.",
  "Faerie Forest Fizz: A sparkling wine with hints of wild berries and an enchanting effervescence.",
  "Rogue's Rye Whiskey: A spicy, daring rye whiskey perfect for those who walk on the wild side.",
  "Goblin's Grog: A murky, potent brew made with fermented mushrooms and a hint of swamp water.",
  "Rat Tail Ale: A surprisingly smooth ale brewed with roasted rat tails for an earthy undertone.",
  "Mushroom Muck Stout: A dark, thick stout with a strong mushroom flavor and hints of underground herbs.",
  "Swampwater Surprise: A dubious, greenish liquor with floating bits of who-knows-what.",
  "Goblin Gutbuster Brew: A strong, acidic beer known for its explosive effects on the unprepared drinker.",
  "Fungus Fizz: A carbonated drink made from various wild fungi, with an unpredictable taste.",
  "Rancid Rat Whiskey: A harsh whiskey distilled with remnants of rodent and a hint of mold.",
  "Bog Berry Brew: A sour, tangy brew made from berries found in goblin swamps.",
  "Goblin Moonshine: An incredibly strong and questionably made liquor, glowing faintly in the moonlight.",
  "Toadstool Tequila: A unique tequila infused with fermented toadstools for an extra kick.",
  "Rotten Root Rum: A sweet, but slightly off rum made from decayed roots and tubers.",
  'Underbridge Unguent: A viscous, bitter drink that goblins swear by for its "medicinal" properties.',
  "Cave Cricket Cider: A cider brewed with cave crickets, adding a peculiar crunch.",
  "Lizard Liquor: A scaly, strong liquor with a hint of lizard tail for extra potency.",
  "Spider Silk Spirits: A clear spirit with a silky mouthfeel, rumored to be filtered through spider webs.",
  "Goblin's Delight Draft: A common goblin drink, easy to gulp but hard to describe.",
  "Moldy Mead: A mead that's been 'enhanced' with a variety of mosses and molds for flavor.",
  "Sewer Water Scotch: A dubious scotch with a hint of sewer aroma, surprisingly popular in goblin circles.",
  "Vile Vinegar Vodka: A pungent vodka made with wild, overripe berries and a hint of vinegar.",
  "Ghoul's Gullet Gin: A gin with an unsettling, meaty flavor, often served in bones.",
  "Frog Foam Froth: A frothy drink made from fermented frog foam, a goblin delicacy.",
  "Troll Tonic: A potent, regenerative tonic brewed with troll toenails.",
  "Wart Wine: A wine with a chunky texture, flavored with various warts and boils.",
  "Carrion Cocktail: A cocktail made with 'aged' meat juices, a goblin's version of a Bloody Mary.",
  "Sludge Slammer: A thick, sludgy drink that's a mixture of everything leftover at the end of the day.",
  "Rat-on-a-Stick: A simple yet popular goblin delicacy, featuring roasted rat skewered on a stick.",
  "Moldy Mushroom Soup: A thick soup made from various mushrooms, some of which are questionably edible, seasoned with whatever the goblins find.",
  "Stewed Swamp Critters: A stew made from various small swamp creatures, seasoned with wild herbs and swamp water.",
  "Bog Bug Broth: A broth teeming with boiled insects and grubs, considered a delicacy among goblins.",
  "Grilled Cave Fish: Fish from underground rivers, grilled over an open flame and often served charred.",
  "Fermented Frog Legs: Frog legs pickled in a mysterious, tangy brine, a goblin favorite.",
  "Toadstool Tacos: Tacos filled with diced toadstools and whatever meat scraps are available, wrapped in a crude bread.",
  "Garbage Goulash: A mix of whatever leftovers and scraps the goblins can scavenge, cooked into a surprisingly edible goulash.",
  "Roasted Rat Ribs: Ribs of rats, slow-roasted and basted with a sauce made from fermented berries.",
  "Sewer Snail Sliders: Small sandwiches filled with cooked sewer snails and a spread of mashed fungi.",
  "Carrion Pie: A pie filled with whatever carrion the goblins can find, seasoned heavily to mask the taste.",
  "Cricket Crunch Salad: A salad made of wild leaves and topped with crunchy roasted crickets.",
  "Lizard Tail Stew: A stew made from lizard tails and wild vegetables, known for its chewy texture.",
  "Pigeon Pot Pie: A pie filled with pigeon meat, wild roots, and a thick, gooey gravy.",
  "Underbridge Omelette: An omelette made from dubious eggs, mixed with chopped up swamp herbs and mushrooms.",
  "Bat Wing Tacos: Tacos filled with fried bat wings, served with a spicy mushroom salsa.",
  "Spider Silk Noodles: Noodles made from a dough that includes fine strands of spider silk, adding a unique texture.",
  "Goblin Gumbo: A thick, spicy stew filled with various meats and vegetables, often spicier than palatable.",
  "Wart Wort Soup: A bitter soup made from warts of various creatures and swamp herbs.",
  "Trash Tumble Turnip: A turnip dish mixed with whatever leftovers are found, often surprisingly hearty.",
  "Fungus Frittata: A crude frittata filled with wild mushrooms and mystery meat.",
  "Boar Brains Biscuits: Biscuits filled with minced boar brains and wild onions.",
  "Maggot Meatloaf: A dense loaf of meat filled with maggots, which are considered a source of extra protein.",
  "Swampweed Wrap: A wrap filled with swamp weeds and small, diced critters.",
  "Goblin 'Delicacy' Dumplings: Dumplings filled with an unpredictable mixture of meats, vegetables, and whatever else is at hand.",
  "Ironforge Stew: A thick, meaty stew with chunks of beef, root vegetables, and stout ale.",
  "Mithril Ale-Braised Boar: Tender boar meat slow-cooked in a mithril ale, with a blend of mountain herbs.",
  "Deep Earth Bread: A dense, crusty bread made with grains from the dwarven heartlands, often served with thick slabs of butter.",
  "Stonebaked Yams: Yams wrapped in clay and baked in hot coals, giving them a unique, smoky flavor.",
  "Mountain Goat Cheese Platter: A selection of rich, aged cheeses made from mountain goat milk.",
  "Forge-Grilled Ribs: Ribs grilled over an open forge, basted with a spicy, smoky sauce.",
  "Gemstone Pudding: A sweet dessert with colorful, crystallized sugars resembling precious gems.",
  "Dwarven Meat Pies: Hearty pies filled with spiced meats and gravy, encased in a thick, buttery crust.",
  "Ale-Soaked Bratwurst: Juicy sausages soaked in ale, then grilled to perfection.",
  "Golden Ale Soup: A creamy soup made with dwarven golden ale and hearty vegetables.",
  "Rune-Engraved Root Vegetables: Root vegetables roasted with herbs and marked with traditional runes for extra flavor.",
  "Crystal Cavern Shrimp: Shrimp caught in underground streams, cooked with garlic and rare spices.",
  "Miner's Mushrooms: Mushrooms stuffed with a mixture of cheese and finely chopped meat, then baked.",
  "Boulder Biscuits: Hearty biscuits that are as filling as they are tasty, often served with rich gravy.",
  "Lava Bread: A spicy bread that incorporates hot peppers and is known for its fiery kick.",
  "Anvil-Pressed Panini: Sandwiches made with thick bread and a variety of meats and cheeses, pressed on a hot anvil.",
  "Silvervein Sausage Stew: A rich stew made with special sausages, vegetables, and a hint of silverleaf for added flavor.",
  "Gneiss Gnocchi: Potato gnocchi served with a robust meat sauce, named after the gneiss rock prevalent in dwarven territories.",
  "Pickled Cavefish: Fish preserved in a brine of herbs and ale, a popular dwarven delicacy.",
  "Barrel-Aged Beef Jerky: Beef jerky aged in whiskey barrels, giving it a unique smoky flavor.",
  "Obsidian Chili: A hot, spicy chili made with black beans and fire-roasted peppers.",
  "Molten Lava Cake: A rich chocolate cake with a warm, flowing center, resembling molten lava.",
  "Hammered Pork: Slow-cooked pork tenderloin, tenderized with a smith's hammer for extra tenderness.",
  "Frostbeard Frosting Cake: A cake with a thick layer of sweet frosting, named after a famous dwarven chef.",
  "Elder Ale Glazed Carrots: Carrots glazed in a reduction of sweet elder ale and honey.",
  "Deep Mountain Stout: A dark, rich stout with notes of coffee and chocolate, brewed in the depths of the mountains.",
  "Golden Forge Ale: A smooth, golden ale with a hint of honey and malt, perfect for quenching thirst after a day at the forge.",
  "Dwarven Whiskey: A strong, peaty whiskey aged in deep underground caverns for a unique flavor.",
  "Stoneheart Mead: A hearty mead made with wild mountain honey, known for its warming effect.",
  "Ironblood Red Wine: A full-bodied red wine with a strong, earthy flavor, as robust as the dwarves who brew it.",
  "Crystal Cavern Cider: A crisp, sparkling cider made with apples grown in the mineral-rich soils near crystal caverns.",
  "Boulder Brew Lager: A traditional lager with a smooth, clean taste, favored by dwarven miners.",
  "Mithril Silver Ale: A light, refreshing ale with a slight metallic tang, reminiscent of mithril.",
  "Rune-Carved Rum: A spiced rum with magical runes carved into the aging barrels for added mystique.",
  "Lava Flow Liquor: A potent, fiery liquor that warms all the way down, like drinking molten lava.",
  "Anvil Ale: A heavy, bitter ale as solid and dependable as an anvil.",
  "Mountain Miner's Malt: A malt whiskey with deep, earthy tones, reflecting the heart of the mountains.",
  "Gemstone Gin: A clear, strong gin infused with herbs and a slight shimmer, like ground gemstones.",
  "Blacksmith's Brandy: A robust brandy with smoky undertones, as if forged by a blacksmith's hands.",
  "Frostbeard Vodka: A crystal-clear vodka distilled in icy conditions, as sharp and crisp as a frostbeard's whiskers.",
  "Elder Dwarf Draft: A traditional draft beer, brewed following ancient recipes passed down through generations.",
  "Ember Elixir: A spicy, warming drink, reminiscent of embers in a dwarven hearth.",
  "Underhill Pilsner: A light pilsner with a smooth finish, perfect for sipping in the cooler underground taverns.",
  "Gneiss Grog: A simple, strong grog named after the gneiss rock, a staple in many dwarven diets.",
  "Barrel-Aged Barleywine: A rich, strong barleywine aged in whiskey barrels for an extra layer of complexity.",
  "Forge Fire Sambuca: A fiery, anise-flavored liqueur that blazes like forge fire when lit.",
  "Cask Strength Cognac: A high-proof cognac, aged in oak casks and enjoyed by the most seasoned of dwarven drinkers.",
  "Dwarven Delight Bock: A darker, malty bock beer that's both sweet and strong.",
  "Mountain Spring Schnapps: A refreshing schnapps made with pure mountain spring water, herbs, and fruits.",
  "Bedrock Bourbon: A smooth, rich bourbon with layers of flavor, as complex as the bedrock it's named after.",
  "Moonlight Mushroom Risotto: A delicate risotto made with mushrooms that only bloom under a full moon, giving a subtle, enchanting flavor.",
  "Sun-Dappled Salad: A light salad with leaves, herbs, and flowers all foraged from sunlit glades.",
  "Starfruit and Elderberry Compote: A sweet, tangy dessert made from starfruits and elderberries, often eaten during celestial events.",
  "Ethereal Eel Sashimi: Thinly sliced eel, served raw, that's been raised in crystal-clear streams.",
  "Forest Fawn Tenderloin: A tender, lean cut of fawn, grilled lightly with a glaze of wild honey.",
  "Grilled Phoenix Feather Fish: A rare fish that's marinated in a mixture of herbs and grilled to perfection, named for its delicate, feather-like scales.",
  "Wild Nymph Nectar Soup: A sweet, rejuvenating soup made with nectar collected by forest nymphs.",
  "Twilight Truffle Tagliatelle: Pasta infused with truffles that bloom at twilight, offering a unique and aromatic flavor.",
  "Elderflower and Lavender Lemonade: A refreshing drink made from elderflowers, lavender, and fresh-squeezed lemon, sparkling with a touch of magic.",
  "Woodland Berry Tart: A light tart made with an assortment of berries found in elven forests, with a flaky, buttery crust.",
  "Mystic Manna Bread: A light, airy bread said to be made from ingredients blessed by Elven deities.",
  "Feywild Fruits Platter: A selection of exotic fruits that are said to come from the Feywild, bursting with supernatural flavors.",
  'Honey-Glazed Pixie Wings: A delicacy of crispy, honey-glazed faux "pixie wings" made from thinly sliced root vegetables.',
  "Sylvan Spring Water: Pure water from a sacred spring, known for its healing and rejuvenating properties.",
  "Glistening Glade Gazpacho: A cold soup made from fresh vegetables and herbs, with a dew-like shimmer.",
  "Enchanted Elk Stew: A hearty stew made from elk meat, slow-cooked with a blend of magical herbs.",
  "Dragonfly Delight: A light, crunchy appetizer made from candied dragonfly wings (no dragonflies harmed; it's a plant-based concoction that resembles wings).",
  "Rune-etched Root Vegetables: Roasted root vegetables etched with ancient elven runes to enhance their natural flavors.",
  "Celestial Ceviche: A dish of raw fish cured in moonlit lemon and lime juices, garnished with edible flowers.",
  "Luminous Lobster Bisque: A creamy lobster bisque that has a subtle glow, made with luminescent plankton.",
  "Baked Griffon Egg Flan: A delicate flan made from griffon eggs, known for their rich, creamy texture.",
  "Gleaming Golden Grouper: A fish dish where the skin of the grouper is prepared to maintain its natural, golden gleam, complemented with light herbs.",
  "Bloomed Berry Blintz: Thin, crepe-like pastries filled with sweet, freshly bloomed berries and a light cream.",
  "Whisperwind Wraps: Thin wraps filled with a mix of vegetables and rare herbs, so light they almost melt in the mouth.",
  "Arcane Antipasto: An appetizer platter with a variety of magical-infused meats, cheeses, and vegetables.",
  "Starlight Wine: A light, sparkling wine that seems to shimmer with captured starlight.",
  "Moonwell Mead: A smooth mead brewed with honey from bees that pollinate only moonlit flowers.",
  "Elderflower Elixir: A delicate, floral liqueur made from elderflowers and infused with a touch of elven magic.",
  "Sunrise Cider: A refreshing cider with hints of citrus and apple, capturing the essence of a crisp dawn.",
  "Forest Nectar Ale: A light ale brewed with a variety of nectars collected from deep forest flowers.",
  "Mistywood Mist: A light, ethereal spirit that appears almost mist-like in the bottle, with a flavor that changes subtly with the drinker's mood.",
  "Feywild Ferment: A whimsical drink with a taste that's ever-changing and enchanting, as unpredictable as the Feywild itself.",
  "Eclipse Brandy: A rich brandy that is aged during lunar eclipses, giving it a unique, otherworldly quality.",
  "Sylvan Spritz: A sparkling, herbal-infused wine with a light, refreshing taste.",
  "Ancient Oak Whiskey: A whiskey aged in barrels made from ancient oak trees, with deep, earthy undertones.",
  "Glimmerglen Gin: A crystal-clear gin infused with botanicals and a slight, natural shimmer reminiscent of a glen bathed in sunlight.",
  "Willowisp Vodka: A smooth, pure vodka that seems to glow faintly in the glass, as if holding a will-o'-the-wisp.",
  "Blossomfall Sake: A floral, delicate sake made from rice grown in elven fields and watered with spring rain.",
  "Lunar Lager: A beer brewed during full moons, capturing a hint of lunar enchantment in each sip.",
  "Thornapple Tequila: A tequila distilled from a fruit that only grows in bramble thickets, with a sharp yet satisfying taste.",
  "Veilwood Vermouth: A sweet, aromatic vermouth infused with herbs and spices from the Veilwood forests.",
  "Raindrop Rum: A light rum distilled from cane sugar grown in the moist, rain-soaked regions of elven lands.",
  "Dewdrop Draught: A beer with a light, refreshing taste, as if imbued with the essence of morning dew.",
  "Twilight Tonic: A tonic that shifts in color from deep blue to purple, mirroring the twilight sky.",
  "Enchanted Elderberry Port: A sweet, rich port wine made from elderberries, each batch blessed with a small enchantment for clarity.",
  "Greenleaf Grappa: A strong, grape-based brandy with hints of various green leaves and herbs, giving it a fresh aftertaste.",
  "Silverstem Schnapps: A crisp, clear schnapps made from a rare plant with silver-hued stems.",
  "Whisperwind Whisky: A smooth, subtle whisky that seems to carry the sound of whispering winds within its flavor.",
  "Ivy Ivy Infusion: A potent, herbal-infused liquor with a complex, layered taste.",
  "Starflower Sherry: A sherry with a slight, natural floral sweetness, aged under a canopy of blooming starflowers.",
  "Clockwork Canapés: Tiny, intricate appetizers that are almost mechanical in their precision, featuring a variety of cheeses, meats, and tiny vegetables.",
  "Sprocket Sausages: Small, gear-shaped sausages, spiced with a mix of sweet and savory flavors, often served with a tangy berry sauce.",
  "Tinkerer's Tapas: A variety of small, experimental dishes, each with a unique flavor combination, encouraging diners to mix and match.",
  "Gadget Grilled Cheese: A sandwich with an array of different cheeses, each layer offering a different texture and flavor, served with a side of tomato bisque.",
  "Whirlygig Wings: Chicken wings coated in a vibrant, zesty sauce, served with a playful presentation that mimics the motion of a wind-up toy.",
  "Inventor's Stew: A hearty stew with a surprising mix of ingredients, from traditional vegetables to more exotic fare, simmered in a rich broth.",
  "Coggle Cheese Platter: An assortment of artisanal cheeses, some infused with unusual ingredients like edible flowers or sweet fruits.",
  "Piston Pie: A savory pie with a rotating selection of fillings, encased in a flaky, buttery crust.",
  "Spring-Loaded Skewers: Skewers of meat and vegetables, prepared with a special seasoning that 'pops' in your mouth.",
  "Gnome-Grown Salad: A salad made from a variety of miniature vegetables grown in gnome gardens, tossed with a light, tangy dressing.",
  "Blinkberry Tartlets: Small tarts filled with blinkberries (berries that briefly shimmer) and topped with a light cream.",
  "Mystic Mushroom Risotto: A creamy risotto made with mushrooms that change color as you eat them, adding a playful twist.",
  "Artificer's Ambrosia: A dessert made with a mix of exotic fruits and sweet creams, arranged in a pattern resembling a gnome invention.",
  "Gearwork Galette: A rustic, open-faced pie with a spiral arrangement of fruits or vegetables, resembling gear teeth.",
  "Illusionist's Ice Cream: A magical ice cream that changes flavors as you eat it, each spoonful a new and unexpected delight.",
  "Enigma Eclairs: Eclairs filled with a mysterious cream that has a flavor which seems to be both familiar and surprising at the same time.",
  "Bewildering Baguettes: Bread with a crispy crust and a soft interior, embedded with a variety of seeds and nuts in whimsical patterns.",
  "Tinkertown Tea Sandwiches: Delicate sandwiches with a variety of creative fillings, perfect for a light snack or tea party.",
  "Mechanist's Meatballs: Meatballs made with a blend of meats and spices, served with a dipping sauce that has a hint of gears and sprockets in its design.",
  "Gnome Nectar Smoothie: A refreshing drink made from a blend of rare fruits and a hint of honey, known for its energizing properties.",
  "Tinkertonic Brew: A bright, bubbling brew with a slight metallic aftertaste, reminiscent of a busy workshop.",
  "Gadgeteer's Grog: A robust grog served in a mug with a miniature, functioning gear system attached.",
  "Inventor's Infusion: A clear spirit infused with various herbs and spices, each bottle a different experimental batch.",
  "Mystic Mead: A mead that subtly changes color when exposed to different lights, with a hint of sweetness.",
  "Cogwheel Cider: A crisp, sparkling cider with a hint of cinnamon, served in a glass with an etched cogwheel design.",
  "Sparkgear Seltzer: A lightly carbonated seltzer with a surprising pop of electric flavor.",
  "Blueprint Brandy: A smooth brandy with notes of oak and vanilla, served in a flask resembling a rolled-up blueprint.",
  "Widget Whiskey: A whiskey with a complex flavor profile, each sip revealing a new layer of taste.",
  "Contraption Cream Ale: A creamy ale with a smooth, rich texture, served with a small, edible mechanical garnish.",
  "Potionmaster's Pilsner: A light pilsner with an herbal aroma, each bottle sealed with a wax stamp resembling an alchemical symbol.",
  "Illusionist's IPA: A hoppy IPA that tricks the senses, making you second guess the flavor profile.",
  "Arcane Absinthe: A potent absinthe with a mystical glow, traditionally served with a special spoon and sugar cube.",
  "Springloaded Stout: A dark, rich stout that seems to have a life of its own once poured, with a cascading effect.",
  "Clockwork Cocktail: A mixed drink with precisely measured ingredients, garnished with a small, edible clock gear.",
  "Gnome-made Gin: A gin with a unique blend of botanicals, each batch slightly different from the last.",
  "Elixir of Enlightenment: A high-alcohol content drink that promises (but doesn't guarantee) brilliant ideas after consumption.",
  "Sprocket Spiced Rum: A spiced rum with hints of cinnamon, nutmeg, and a touch of metallic spice.",
  "Prismatic Port: A sweet port wine with a prismatic hue, changing colors as you swirl the glass.",
  "Engineer's Eau-de-vie: A clear, strong spirit distilled from gnome-grown fruits, often used as a base for inventive cocktails.",
  "Mecha-Mead: A traditional mead with a twist - a hint of nuts and bolts flavor, paying homage to the gnomish love for mechanics.",
  "Hearty Harvest Stew: A comforting stew made with root vegetables and tender meat, slow-cooked over an open fire.",
  "Meadowbrook Pie: A savory pie filled with chicken, mushrooms, and creamy sauce, topped with a golden crust.",
  "Bountiful Berry Tart: A sweet tart made with a mix of fresh berries from the local forests.",
  "Riverside Fish Fry: Freshly caught fish, lightly battered and fried, served with a side of crispy potatoes.",
  "Summerhill Sausages: Plump, herby sausages, often grilled outdoors and served with a dollop of spicy mustard.",
  "Golden Grain Bread: A dense, freshly baked bread made from various grains, served with rich, creamy butter.",
  "Garden Vegetable Quiche: A delightful quiche filled with seasonal garden vegetables and a blend of cheeses.",
  "Cheese and Chutney Platter: A selection of homemade cheeses paired with sweet and savory chutneys.",
  "Pumpkin and Leek Soup: A creamy soup combining the sweetness of pumpkin with the subtle flavor of leeks.",
  "Lullaby Lamb Roast: Slow-roasted lamb with a herb crust, served with roasted vegetables and mint sauce.",
  "Hilltop Honey Ale: A smooth, sweet ale brewed with local honey.",
  "Riverbank Red Wine: A medium-bodied red wine with hints of berry and oak.",
  "Dandelion Mead: A light, refreshing mead with a subtle hint of dandelion.",
  "Orchard Apple Cider: A crisp cider made from the apples of nearby orchards, with both sweet and tart varieties.",
  "Barley Brew Beer: A traditional beer, favored for its robust and hearty flavor.",
  "Thistleberry Wine: A sweet wine made from the juice of thistleberries, a halfling favorite.",
  "Sunset Stout: A dark, rich stout with notes of caramel and coffee.",
  "Meadowflower Malt: A malt liquor infused with fragrant meadow flowers.",
  "Golden Grain Whiskey: A smooth whiskey with hints of vanilla and oak, distilled from fine grains.",
  "Forest Fruit Punch: A potent, fruity alcoholic punch made with a mix of forest berries and spirits.",
  "Bog Toad Stew: A rich stew made with toad meat, wild swamp herbs, and root vegetables.",
  "Cattail Cornbread: A dense, moist cornbread made with cattail flour, giving it a unique texture and flavor.",
  "Marsh Muck Gumbo: A thick, flavorful gumbo with a variety of swamp meats, like snake, frog, and crayfish, spiced with swamp peppers.",
  "Lily Pad Pancakes: Savory pancakes made from ground lily pad flour, often served with a side of wild berry compote.",
  "Crawdad Creole: Spicy crawfish cooked with tomatoes, onions, and a blend of swamp spices.",
  "Swamp Reed Soup: A light, herby soup made from tender young swamp reeds and other foraged greens.",
  "Mudcat Grill: Grilled catfish seasoned with wild swamp herbs and served with a side of wild rice.",
  "Frog Leg Fry-Up: Crispy, fried frog legs seasoned with a mix of local herbs and spices, served with a tangy dipping sauce.",
  "Water Moccasin Jerky: Thinly sliced, dried snake meat, often eaten as a protein-rich snack.",
  "Willow Bark Tea: A medicinal tea made from the bark of willow trees, known for its soothing properties.",
  "Swamp Berry Pie: A sweet pie filled with a mix of tart swamp berries, topped with a crumbly crust.",
  "Alligator Skewers: Marinated alligator meat, grilled on skewers with swamp vegetables.",
  "Catfish Chowder: A creamy chowder with chunks of catfish, potatoes, and corn, seasoned with bay leaves and thyme.",
  "Duckweed Salad: A fresh salad made from duckweed, often tossed with a light vinaigrette and topped with toasted nuts.",
  "Silt Root Roast: Roasted roots and tubers, dug up from the swamp floor, seasoned and slow-roasted until tender.",
  "Mangrove Fruit Compote: A sweet and tangy compote made from the fruits of the mangrove tree.",
  "Bayou Biscuits: Fluffy biscuits made with traditional ingredients, served with honey or molasses.",
  "Snapping Turtle Soup: A hearty soup made with snapping turtle meat, slow-cooked with a variety of vegetables.",
  "Mossy Log Mushrooms: Wild mushrooms that grow on damp logs, sautéed with garlic and butter.",
  "Peat Pudding: A rich, earthy dessert pudding made with peat and sweetened with local honey.",
  "Bogwater Brew: A murky, dark beer with a surprisingly smooth taste, brewed with local swamp grains and moss.",
  "Cattail Mead: A sweet mead made from fermented cattail pollen and wild honey.",
  "Marshroot Moonshine: A strong, clear spirit distilled from swamp roots, known for its potent kick.",
  "Willow Whiskey: A smooth whiskey infused with willow bark, giving it a subtle, woody flavor.",
  "Mangrove Rum: A dark rum aged with mangrove wood, imparting a unique, earthy undertone.",
  "Frogspawn Fizz: A sparkling, light alcoholic drink with a hint of lime, garnished with floating, edible jelly beads resembling frogspawn.",
  "Swamp Berry Cider: A tart and sweet cider made from a variety of swamp berries, offering a refreshing taste.",
  "Lily Pad Liqueur: A floral liqueur made from lily pad nectar, often served in small, delicate glasses.",
  "Peat Bog Porter: A rich, deep porter with notes of peat and a hint of smokiness.",
  "Mudflat Mule: A cocktail with a strong kick, made with vodka, ginger beer, and a splash of lime, served in a clay mug.",
  "Reed Reed Ale: A light ale brewed with reeds and marsh herbs, giving it a unique, earthy flavor.",
  "Bayou Bourbon: A smooth bourbon with a hint of spice and sweetness, aged in barrels made from swamp oak.",
  "Turtle Shell Tequila: A tequila aged in turtle shells, giving it a unique, earthy flavor profile.",
  "Alligator Ale: A robust ale with a hint of caramel, said to be as bold as the alligators that roam the swamps.",
  "Duckweed Daiquiri: A frozen daiquiri made with duckweed-infused syrup, offering a vibrant green color and refreshing taste.",
  "Snapping Turtle Stout: A stout with a thick, creamy texture and a hint of chocolate, brewed with traditional swamp ingredients.",
  "Mossy Malt: A malt liquor with hints of moss and earth, offering a deep, rich flavor.",
  "Swampweed Schnapps: A herbal schnapps made from a variety of swamp weeds, known for its medicinal properties.",
  "Crocodile Cooler: A cocktail made with rum, tropical fruit juices, and a hint of swamp herbs, served chilled.",
  "Siltwater Sling: A murky cocktail made with gin, swamp herbs, and a touch of lemon, served over silt-filtered ice.",
  "Chimera Chops: Grilled chops from a chimera, offering a unique combination of flavors from each of the creature's parts.",
  "Basilisk Broth: A soup made from basilisk meat, known for its intense flavors and reputed (and purely mythical) petrifying properties.",
  "Griffon Egg Omelette: An omelette made from the enormous eggs of a griffon, enough to feed an entire party.",
  "Direwolf Stew: A hearty stew made from the meat of a direwolf, offering a rich and gamey flavor.",
  "Phoenix Feather Fricassee: A dish prepared with the feathers of a phoenix, which impart a slight smokiness and a hint of spice as they dissolve in the cooking process.",
  "Dragon Scale Tacos: Tacos with a shell made from dragon scales, providing a crunchy texture and a hint of elemental magic.",
  "Manticore Mane Meatballs: Spicy meatballs made from the mane of a manticore, believed to give the diner a fierce strength.",
  "Pixie Dust Parfait: A light, sweet dessert layered with fruits, creams, and a sprinkling of pixie dust for a bit of enchantment.",
  "Cockatrice Wings: Spicy and tangy wings from a cockatrice, known for their tender meat.",
  "Roc Roast: A massive roast from the legendary roc bird, typically served at large gatherings or feasts.",
  "Troll Tongue Terrine: A challenging dish made from troll tongues, known for their unique texture and regenerative properties.",
  "Kraken Calamari: Rings of calamari from a kraken, much larger and more flavorful than ordinary squid.",
  "Gelatinous Cube Jelly: A jiggly, translucent dessert made from a gelatinous cube, with bits of fruit and sweet items suspended within.",
  "Beholder Eye Stew: A rare and exotic stew made using the eye of a beholder, known for its powerful and unpredictable flavors.",
  "Merfolk Scales Sushi: Sushi wrapped in delicate merfolk scales, which add a shimmering, iridescent quality to the dish.",
  "Owlbear Drumsticks: Hearty and large, these drumsticks offer a rich, wild taste unlike any poultry.",
  "Elemental Essence Elixir: A drinkable potion made from the essence of elemental creatures, each sip offering a burst of elemental energy.",
  "Vampire Vine Wine: A deep, rich wine made from grapes grown in vampire-infested vineyards, with a hint of iron.",
  "Fairy Fritters: Small, light pastries dusted with fairy sugar, causing a slight floating sensation when eaten.",
  "Lich's Dust Spice Mix: A rare and potent spice mix made from the remains of a vanquished lich, offering a deep, umami flavor with a hint of magic.",
  "Ghoul Gizzards Stew: A thick stew made from the gizzards of ghouls, known for its unnerving texture.",
  "Rotten Fruit Chutney: A chutney made from overripe, almost decomposed fruits, surprisingly sweet with a hint of fermentation.",
  "Maggot Cheese Spread: A creamy cheese that's been fermented with live maggots, giving it a unique and wriggly texture.",
  "Slime Mold Soup: A soup made from dungeon-grown slime molds, featuring a slimy yet savory broth.",
  "Blood Pudding: Traditional blood pudding, but made with the blood of exotic creatures, giving it an unusual twist.",
  "Fermented Fish Eyes: Considered a delicacy in some cultures, these fish eyes are fermented until they reach a jelly-like consistency.",
  "Troll Toe Jam: A spread made from the toe jam of trolls, mixed with herbs to mask the odor and improve the taste.",
  "Pickled Pixie Wings: Pixie wings preserved in a pungent vinegar solution, creating a sour and slightly magical snack.",
  "Ogre Earwax Candles: A bizarre dish where the wax from ogre ears is used to create edible candles, often flavored with spices.",
  "Stirge Sucker Soup: A soup containing the bloodsucking stirges, known for their potent, iron-rich flavor.",
  "Cockatrice Intestine Sausage: Sausage made from the intestines of a cockatrice, offering a risky yet rewarding culinary experience.",
  "Basilisk Liver Pâté: A rich, creamy pâté made from the liver of a basilisk, often inducing a heavy, lethargic feeling after consumption.",
  "Zombie Brain Fritters: Fried fritters containing the brains of zombies, seasoned heavily to mask the decaying taste.",
  "Spectral Jelly: A quivering jelly made from condensed ghost essence, consuming it might cause temporary etherealness.",
  "Graveyard Mushrooms: Mushrooms that only grow in graveyards, with a musty, earthy flavor.",
  "Wraith Wisp Whisky: A whisky infused with the essence of wraiths, causing a chilling sensation upon consumption.",
  "Dragon Dropping Truffles: Truffles supposedly made from dragon droppings, prized for their extreme rarity and unique taste.",
  "Hag Hair Pasta: Pasta made with strands of hag hair, offering a disturbingly chewy texture.",
  "Vulture Vomit Vinegar: A sour vinegar made from the regurgitated contents of vultures, used as a dressing or marinade.",
  "Wormwood Worm Wine: A wine fermented with wriggling worms, believed to have hallucinogenic properties.",
  "Ethereal Ectoplasm Soup: A shimmering broth made from ethereal ectoplasm, offering a taste that's both otherworldly and comforting.",
  "Crystal Shard Salad: A crunchy salad featuring thinly sliced, edible crystal shards that add a sparkling, mineral flavor.",
  "Manafruit Compote: A sweet dish made from mana-infused fruits, providing a burst of energy to those who eat it.",
  "Changeling Chutney: A chutney that changes its flavor to complement whatever it's served with, made using shape-shifting fruits.",
  "Voidberry Tart: A tart made from voidberries, which taste different to each individual based on their personal preferences.",
  "Elemental Ice Cream: An ice cream where each scoop is infused with a different elemental essence, such as fire, air, earth, or water.",
  "Astral Ale: A beer brewed with a hint of stardust, causing the liquid to shimmer with a celestial light.",
  "Goblin Grog: Made with fermented mushrooms and swamp herbs, this grog has a potent and unpredictable effect.",
  "Djinni's Draft: A mystical drink that grants a feeling of weightlessness after consumption.",
  "Siren's Sangria: Infused with enchanted seaweed and sea salt, this sangria temporarily enhances the drinker's vocal abilities.",
  "Mimic Malt: A malt beverage that seems to change its taste to match the drinker’s favorite flavors.",
  "Mountain Dwarf Delicacy: Ironbloom Mushrooms Stew - A hearty stew made with mushrooms that grow inside dark caves, rich in minerals.",
  " Sunleaf Salad: A delicate salad made from leaves that only grow in sunlight-dappled clearings.",
  "Blindfish Ceviche: A dish prepared with blindfish, a delicacy in the underdark, served raw and seasoned with exotic underground herbs.",
  "Sea Drake Skewers: Grilled skewers of sea drake meat, known for its tender texture and salty flavor, popular in coastal towns.",
  "Sandworm Jerky: A staple for desert travelers, this jerky is made from giant sandworms, known for being nutritious and long-lasting.",
  "Frostfire Mead: A mead that warms the body from the inside, popular in cold, northern regions.",
];
const parseColonArray = (items, fields) => {
  const test = ["Item1: Value", "Item2: Value2", "Item3: Value3"];

  const json = [];

  test.forEach((value) => {
    let str = value.split("");
  });
};

module.exports = parseColonArray;
