const { getRandomElement } = require("./random.util");

const templates = [
  { template: "The ${color} ${noun}", parts: ["colors", "nouns"] },
  { template: "${noun} of the ${noun}", parts: ["nouns", "nouns"] },
  { template: "The ${adjective} ${noun}", parts: ["adjectives", "nouns"] },
  { template: "${noun} and ${noun}", parts: ["nouns", "nouns"] },
  { template: "${animal} and ${noun}", parts: ["animals", "nouns"] },
  { template: "${noun}'s ${feature}", parts: ["nouns", "features"] },
  { template: "The ${verb} ${noun}", parts: ["verbs", "nouns"] },
  { template: "The ${color} ${animal}", parts: ["colors", "animals"] },
  { template: "The ${verb} ${animal}", parts: ["verbs", "animals"] },
  { template: "The ${adjective} ${animal}", parts: ["adjectives", "animals"] },
  { template: "The ${verb} ${feature}", parts: ["verbs", "animals"] },
];

const nouns = [
  "Dragon",
  "Knight",
  "Crown",
  "Chalice",
  "Phoenix",
  "Goblin",
  "Wizard",
  "Forest",
  "Harbor",
  "Castle",
  "Raven",
  "Dagger",
  "Griffin",
  "Ship",
  "Tower",
  "Flame",
  "Hammer",
  "Wolf",
  "Eagle",
  "Falcon",
  "Bear",
  "Lion",
  "Sword",
  "Gem",
  "Star",
  "Moon",
  "Sun",
  "Throne",
  "Anchor",
  "Serpent",
  "Owl",
  "Scroll",
  "Tome",
  "Giant",
  "Pirate",
  "Elf",
  "Dwarf",
  "Mage",
  "Specter",
  "Meadow",
  "Willow",
  "Oak",
];
const adjectives = [
  "Mystic",
  "Ancient",
  "Hidden",
  "Golden",
  "Cursed",
  "Enchanted",
  "Sleepy",
  "Bustling",
  "Lonely",
  "Frosty",
  "Whispering",
  "Singing",
  "Roaring",
  "Dancing",
  "Laughing",
  "Drunken",
  "Haunted",
  "Luminous",
  "Stormy",
  "Rugged",
  "Serene",
  "Fiery",
  "Crimson",
  "Emerald",
  "Silver",
  "Rusty",
  "Weary",
  "Wandering",
  "Wild",
  "Sacred",
  "Eerie",
  "Gloomy",
  "Sunny",
  "Misty",
  "Sapphire",
  "Burning",
  "Frozen",
  "Howling",
  "Peaceful",
  "Thorny",
];
const features = [
  "Inn",
  "Tavern",
  "Alehouse",
  "Pub",
  "Lodge",
  "Bar",
  "Brewery",
  "Cantina",
  "Rest",
  "Retreat",
  "Haven",
  "Hideaway",
  "Sanctuary",
  "Hall",
  "House",
  "Grove",
  "Garden",
  "Den",
  "Cellar",
  "Roost",
  "Nest",
  "Refuge",
  "Joint",
  "Spot",
  "Stop",
  "Cove",
  "Corner",
  "Point",
  "Station",
  "Depot",
  "Cabin",
  "Shack",
  "Hearth",
  "Portal",
  "Domain",
  "Fort",
  "Keep",
  "Tower",
  "Castle",
  "Palace",
];
const verbs = [
  "Dancing",
  "Singing",
  "Roaring",
  "Whispering",
  "Laughing",
  "Feasting",
  "Brewing",
  "Glowing",
  "Sailing",
  "Wandering",
  "Dreaming",
  "Fighting",
  "Charming",
  "Burning",
  "Frosting",
  "Thundering",
  "Shining",
  "Murmuring",
  "Crafting",
  "Guarding",
  "Hunting",
  "Fishing",
  "Flying",
  "Weaving",
  "Howling",
  "Gazing",
  "Gathering",
  "Looming",
  "Creeping",
  "Exploring",
  "Drifting",
  "Soaring",
  "Seeking",
  "Rising",
  "Fading",
  "Gliding",
  "Resting",
  "Wishing",
  "Calling",
  "Marching",
];
const colors = [
  "Crimson",
  "Emerald",
  "Sapphire",
  "Golden",
  "Silver",
  "Ruby",
  "Amber",
  "Azure",
  "Scarlet",
  "Indigo",
  "Violet",
  "Bronze",
  "Ivory",
  "Jade",
  "Midnight",
  "Ebony",
  "Snowy",
  "Rusty",
  "Auburn",
  "Turquoise",
  "Lavender",
  "Peach",
  "Cobalt",
  "Cerulean",
  "Fuchsia",
  "Maroon",
  "Olive",
  "Teal",
  "Copper",
  "Magenta",
  "Tangerine",
  "Charcoal",
  "Aquamarine",
  "Coral",
  "Mint",
  "Rose",
  "Taupe",
  "Lime",
  "Mustard",
  "Navy",
];
const animals = [
  "Dragon",
  "Wolf",
  "Bear",
  "Raven",
  "Eagle",
  "Fox",
  "Lion",
  "Owl",
  "Falcon",
  "Serpent",
  "Hawk",
  "Horse",
  "Badger",
  "Boar",
  "Griffin",
  "Deer",
  "Crow",
  "Sparrow",
  "Panther",
  "Unicorn",
  "Pegasus",
  "Dove",
  "Rat",
  "Bat",
  "Swan",
  "Peacock",
  "Otter",
  "Lynx",
  "Elk",
  "Phoenix",
  "Koi",
  "Frog",
  "Toad",
  "Mongoose",
  "Jackal",
  "Hyena",
  "Leopard",
  "Tiger",
  "Goat",
  "Salamander",
];

const parts = {
  nouns,
  adjectives,
  features,
  verbs,
  colors,
  animals,
};

const generateName = (seed) => {
  let template = getRandomElement(seed + "tavernTemplate", templates);
  let partsArray = template.template.split(/\$\{[^}]+\}/);
  let tavernName = partsArray[0];

  template.parts.forEach((part, i) => {
    let randomPart = getRandomElement(seed + part + i, parts[part]);
    tavernName += randomPart + (partsArray[i + 1] || "");
  });

  return tavernName;
};

module.exports = {
  generateName,
};
